### PR TITLE
Update de-DE.lang

### PR DESCRIPTION
**Pull request by Hawkeye1909**
Updated translation according to english / config file

Removed:
allowSelect = Auswahl erlauben
sizes = Gr&ouml;ssen
styles = Styles
styles.btn = Button Style

### CODE REVIEW

**Comment by kevinchappell** [comment]
Good updates. I just merged some previous changes to de-DE.lang which caused some conflicts. Could you resolve the conflicts? I had a look but am not sure about some of the words.

**Comment by Hawkeye1909** [comment]
Not sure about the checkbox translation either. "Kontrollkästchen" is the right translation but "Checkbox" should be common to people creating forms ...

**Comment by kevinchappell** [comment]
@Hawkeye1909 good point. merging

**Comment by Hawkeye1909** [comment]
Found a minor thing to change and don't want to open a pull request for it. If you don't mind changing it in master:
It has to be "Schließen" `Schlie&szlig;en` not "Schliessen" - except you're from Switzerland ...

**Comment by kevinchappell** [comment]
no problem, can you confirm this is correct? https://github.com/kevinchappell/formBuilder-languages/pull/14

**Pull request merged**
